### ISSUE TITLE
issue on the website

### ISSUE THREAD

**Issue by drpark** [Mean-Finance/dca-v2-core#239]
impossible to access open positions

Request URL:
https://api.mean.finance/v2/transforms/to-underlying
Request Method:
POST
Status Code:
500 Internal Server Error

**Comment by 0xsambugs** [comment]
Hey @drpark !
That's weird, it seems to be working for me right now.

Care to come to our discord (https://discord.mean.finance) so we can help you out more easily? We'll be waiting for you on the #support channel 😄

**Comment by drpark** [comment]
hello @0xsambugs everything is working right now! thank you for the answer.
